#!/bin/bash
# sirene
# Bom para chamar a atenção dos colegas de trabalho :)

echo -ne "\033[11;900]" # Cada bipe dura quase um segundo
while :
do
    echo -ne "\033[10;500]"; sleep 1 # Tom alto (agudo)
    echo -ne "\033[10;400]"; sleep 1 # Tom baixo (grave)
done
